export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_ERROR = "GET_REVIEWS_ERROR";
export const LIKE_REVIEW = "LIKE_REVIEW";
export const DISLIKE_REVIEW = "DISLIKE_REVIEW";